### ISSUE TITLE
Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '.\DotNetCoreReactREST\ClientApp\src'

### ISSUE THREAD

**Issue by AizenSousuke** [AizenSousuke/DotNetCoreReactREST#18]
Branch: Frontend Development
`
Failed to compile
./src/App.js
Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '.\DotNetCoreReactREST\ClientApp\src'
This error occurred during the build time and cannot be dismissed.
`

Is bootstrap supposed to be added or just use the cdn version?

**Comment by TNortnern** [comment]
yarn or npm install fixes this
